Repository ncar-xdev/xpersist, pull requests merged in 2021-12, with the labels that each got.

#36 Update CI
  .github/ISSUE_TEMPLATE/bugreport.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yaml
  .github/workflows/ci.yaml
  .github/workflows/linting.yaml
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  setup.py
Labels: maintenance

#39 Add sphinx docs
  docs/Makefile
  docs/environment.yml
  docs/make.bat
  docs/source/conf.py
  docs/source/how-to-guides/index.md
  docs/source/index.md
  docs/source/reference/cache.md
  docs/source/reference/index.md
  docs/source/reference/prefect.md
  docs/source/reference/registry.md
  docs/source/tutorials/index.md
  readthedocs.yml
Labels: documentation

#44 Update README
  README.md
Labels: documentation

#45 Add `get_artifact()` method
  docs/source/reference/index.md
  docs/source/tutorials/index.md
  tests/test_cache.py
  xpersist/cache.py
Labels: enhancement

#46 Update docs
  docs/source/conf.py
  docs/source/how-to/install-xpersist.md
  docs/source/reference/index.md
  docs/source/tutorials/index.md
  xpersist/cache.py
  xpersist/serializers.py
Labels: documentation

#41 Properly use kwargs for prefect's result target templating
  xpersist/prefect/result.py
Labels: enhancement

#47 Add docs on target templating
  docs/source/how-to/use-xpersist-with-prefect.md
Labels: documentation

#48 Record additional metadata when caching artifact
  docs/source/how-to/use-xpersist-with-prefect.md
  xpersist/cache.py
  xpersist/prefect/result.py
Labels: documentation, enhancement

#50 Update PyPI release workflow
  .github/workflows/pypi-release.yaml
  .github/workflows/pypi.yaml
Labels: maintenance

#52 Fix local ModuleNotFoundError
  ci/environment-upstream-dev.yml
  ci/environment.yml
  setup.py
  xpersist/__init__.py
  xpersist/prefect/__init__.py
Labels: bug

#53 Use find_packages()
  setup.py
Labels: enhancement

#54 Add pandas Serializers
  .github/workflows/ci.yaml
  ci/environment-upstream-dev.yml
  ci/environment.yml
  setup.cfg
  tests/test_cache.py
  tests/test_serializers.py
  xpersist/serializers.py
Labels: enhancement

#55 Update docs: add section on serializers
  docs/source/tutorials/index.md
Labels: documentation

#58 Replace `delitems()` with `delete()`
  docs/source/tutorials/index.md
  tests/test_cache.py
  xpersist/cache.py
  xpersist/prefect/result.py
Labels: bugfix

#59 Raise error when on_duplicate_key is set to `raise_error`
  tests/test_cache.py
  xpersist/cache.py
Labels: enhancement
